// Compile all JSON Schema files to a single packages/types/index.ts
// Run directly: node packages/types/generate.mjs
// Or via:       make types

import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const abs = (f) => resolve(__dirname, f);

const schemas = ['case.schema.json', 'review.schema.json', 'score.schema.json'];

const opts = {
  additionalProperties: false,
  unknownAny: false,
  strictIndexSignatures: true,
  bannerComment: '',
};

const chunks = await Promise.all(schemas.map((s) => compileFromFile(abs(s), opts)));

const banner = [
  '// Generated by packages/types/generate.mjs — do not edit manually.',
  '// Source of truth: packages/types/*.schema.json',
  '// Regenerate: make types',
  '',
  '',
].join('\n');

writeFileSync(abs('index.ts'), banner + chunks.join('\n'));
console.log('✓ packages/types/index.ts');
