// Generated by packages/types/generate.mjs — do not edit manually.
// Source of truth: packages/types/*.schema.json
// Regenerate: make types

export type Action = "approve" | "reject" | "escalate" | "ask_evidence" | "flag_assumption";
export type FailureMode =
  | "one_off_as_recurring"
  | "ignoring_source_evidence"
  | "overconfident_incomplete_data"
  | "wrong_cost_category"
  | "cashflow_vs_pnl"
  | "accrual_vs_cash"
  | "materiality_ignored"
  | "revenue_recognition_timing";

/**
 * A finance scenario presented to the analyst for review. hiddenTruth is never sent to the client.
 */
export interface Case {
  /**
   * Zero-padded number + snake_case slug, e.g. 001_marketing_variance
   */
  id: string;
  title: string;
  category:
    | "Revenue Recognition"
    | "Variance Analysis"
    | "Reconciliation"
    | "Payroll & Accruals"
    | "Inventory"
    | "Lease Accounting"
    | "Collections & AR"
    | "CapEx vs OpEx"
    | "FX Revaluation"
    | "Stock-Based Compensation";
  difficulty: "easy" | "medium" | "hard";
  /**
   * @minItems 4
   * @maxItems 8
   */
  dataset:
    | [DataRow, DataRow, DataRow, DataRow]
    | [DataRow, DataRow, DataRow, DataRow, DataRow]
    | [DataRow, DataRow, DataRow, DataRow, DataRow, DataRow]
    | [DataRow, DataRow, DataRow, DataRow, DataRow, DataRow, DataRow]
    | [DataRow, DataRow, DataRow, DataRow, DataRow, DataRow, DataRow, DataRow];
  /**
   * The AI-generated analysis shown to the analyst — sounds confident, contains the hidden mistake
   */
  aiNarrative: string;
  /**
   * The action the AI recommends (often wrong)
   */
  aiRecommendation: "approve" | "reject" | "escalate" | "ask_evidence" | "flag_assumption";
  hiddenTruth: HiddenTruth;
}
/**
 * One row of the tabular financial dataset shown to the analyst
 */
export interface DataRow {
  account: string;
  /**
   * Budgeted amount in USD
   */
  budget: number;
  /**
   * Actual amount in USD
   */
  actual: number;
  /**
   * actual − budget; positive = favorable
   */
  variance: number;
  notes?: string;
  /**
   * AI has flagged this row as anomalous
   */
  flagged?: boolean;
}
/**
 * Scoring ground-truth — never exposed to the analyst
 */
export interface HiddenTruth {
  /**
   * The action(s) a competent analyst should take
   *
   * @minItems 1
   */
  correctDecision: [Action, ...Action[]];
  /**
   * One sentence: what the AI got wrong
   */
  correctIssueSummary: string;
  /**
   * 3–4 sentences: what an experienced analyst would notice and do differently
   */
  expertFeedback: string;
  /**
   * Specific documents or data an expert would pull before deciding
   *
   * @minItems 1
   */
  evidenceToRequest: [string, ...string[]];
  aiFailureMode: FailureMode;
}

/**
 * A junior analyst's submission for a case
 */
export interface Review {
  id: string;
  /**
   * Foreign key to Case.id
   */
  case_id: string;
  user_id: string;
  /**
   * The action the analyst chose from the action bar
   */
  action: "approve" | "reject" | "escalate" | "ask_evidence" | "flag_assumption";
  /**
   * The analyst's written reasoning (free text)
   */
  reasoning: string;
  /**
   * Elapsed seconds from case load to submission
   */
  time_spent_seconds: number;
  submitted_at: string;
}

export type CriterionName = "caught_main_issue" | "over_trusted_ai" | "escalated_appropriately" | "explanation_quality";
/**
 * Drives score-card color in the UI (green / rose / amber / indigo)
 */
export type Tone = "pass" | "fail" | "partial" | "neutral";

/**
 * The system's evaluation of a Review against the case's hiddenTruth
 */
export interface Score {
  id: string;
  review_id: string;
  /**
   * Exactly one entry per CriterionName, in order
   *
   * @minItems 4
   * @maxItems 4
   */
  criteria: [CriterionScore, CriterionScore, CriterionScore, CriterionScore];
  /**
   * Mean of the four criterion scores × 10
   */
  total: number;
  /**
   * LLM-generated paragraph comparing analyst's work to the expert baseline
   */
  feedback_summary: string;
  /**
   * LLM-generated paragraph: what an expert analyst would have noticed and done
   */
  expert_would_do: string;
  /**
   * Signed shift applied to user's running Over-Trust Index. Positive = appropriately skeptical; negative = over-trusted AI. Derived from over_trusted_ai.score.
   */
  over_trust_delta: number;
}
export interface CriterionScore {
  name: CriterionName;
  score: number;
  tone: Tone;
  /**
   * Verbatim evidence or explanation produced by the scoring LLM
   */
  rationale: string;
}
