SCHEMA_DIR := packages/types
SCHEMAS    := $(SCHEMA_DIR)/case.schema.json \
              $(SCHEMA_DIR)/review.schema.json \
              $(SCHEMA_DIR)/score.schema.json

.PHONY: types
types: $(SCHEMA_DIR)/index.ts $(SCHEMA_DIR)/python/models.py

# ── TypeScript ──────────────────────────────────────────────────────────────
$(SCHEMA_DIR)/index.ts: $(SCHEMAS) $(SCHEMA_DIR)/generate.mjs
	node $(SCHEMA_DIR)/generate.mjs

# ── Python (Pydantic v2) ─────────────────────────────────────────────────────
$(SCHEMA_DIR)/python/models.py: $(SCHEMAS)
	@mkdir -p $(SCHEMA_DIR)/python
	datamodel-codegen \
		--input $(SCHEMA_DIR)/case.schema.json \
		--input-file-type jsonschema \
		--output $(SCHEMA_DIR)/python/_case.py \
		--output-model-type pydantic_v2.BaseModel \
		--no-stamp
	datamodel-codegen \
		--input $(SCHEMA_DIR)/review.schema.json \
		--input-file-type jsonschema \
		--output $(SCHEMA_DIR)/python/_review.py \
		--output-model-type pydantic_v2.BaseModel \
		--no-stamp
	datamodel-codegen \
		--input $(SCHEMA_DIR)/score.schema.json \
		--input-file-type jsonschema \
		--output $(SCHEMA_DIR)/python/_score.py \
		--output-model-type pydantic_v2.BaseModel \
		--no-stamp
	@printf '# Generated by datamodel-codegen — do not edit manually.\n# Source of truth: packages/types/*.schema.json\n# Regenerate: make types\n\n' > $@
	@cat $(SCHEMA_DIR)/python/_case.py   >> $@
	@printf '\n\n' >> $@
	@cat $(SCHEMA_DIR)/python/_review.py >> $@
	@printf '\n\n' >> $@
	@cat $(SCHEMA_DIR)/python/_score.py  >> $@
	@rm -f $(SCHEMA_DIR)/python/_case.py \
	       $(SCHEMA_DIR)/python/_review.py \
	       $(SCHEMA_DIR)/python/_score.py
	@echo "✓ $(SCHEMA_DIR)/python/models.py"

.PHONY: api-dev
api-dev:
	cd apps/api && uv run uvicorn app.main:app --reload --port 8000
